import type { NextPage } from "next";

import Header from "src/components/header";
import { Text } from "@chakra-ui/react";

import backgroundVideo from '../styles/background.mp4'

const IndexPage: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Homely</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="./styles/background.mp4" />
      </Head>

      <main>
        <div className="backgroundVideo">
          <video autoPlay loop muted id='video'>
            <source src={backgroundVideo} type='video/mp4'>
          </video>
          </div>
          <div className="container">
            <Text fontSize="6xl">Welcome Page</Text>
          </div>
      </main>
   </div>
  );
};

export default IndexPage;
