import type { NextPage } from 'next';
import Head from 'next/head';

const IndexPage: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Homely</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='./styles/background.mp4' />
      </Head>

      <main>
        <div className='backgroundVideo'>
          <video autoPlay loop muted id='video'>
            <source src={'/background.mp4'} type='video/mp4' />
          </video>
          <div className='HomelyWelcomePage'>
            <h1 className='HomelyHeading'>Welcome to Homely</h1>
          </div>
        </div>
      </main>
    </div>
  );
};

export default IndexPage;
