# For Job Posters: Add a Job Posting
POST http://localhost:3000/api/add-job HTTP/1.1
Content-Type: application/json

{
    "jobTitle":"Mc Donalds Servant",
    "description":"Help on the front desk at Mc Donalds",
    "deadline": 1650377823000,
    "workHours":8,
    "maxCapacity":5,
    "applied": 0,
    "location": "2241 Avenue U, Brooklyn NY",
    "token":"eyJhbGciOiJSUzI1NiIsImtpZCI6IjQ2NDExN2FjMzk2YmM3MWM4YzU5ZmI1MTlmMDEzZTJiNWJiNmM2ZTEiLCJ0eXAiOiJKV1QifQ.eyJ1c2VyVHlwZSI6IkFkbWluIiwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2hvbWVseS1kYjhlMiIsImF1ZCI6ImhvbWVseS1kYjhlMiIsImF1dGhfdGltZSI6MTY0ODk5NTkwMCwidXNlcl9pZCI6InF5TVJheHQxVVhmNmdZbFE1MExtc0FVd2xXWTIiLCJzdWIiOiJxeU1SYXh0MVVYZjZnWWxRNTBMbXNBVXdsV1kyIiwiaWF0IjoxNjQ4OTk1OTAwLCJleHAiOjE2NDg5OTk1MDAsImVtYWlsIjoid2FuZ25lbHNvbjJAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbIndhbmduZWxzb24yQGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.awCLPzlXgfiilgm7xEAZffgDGve_c-rtIogaJx8jyQGGiWAQnvGPUgCV_5U7piqRAxua0_RkumlQ1hrpJVGF_Ny3ISblfzA8LIWiZD8Qzpg6BBeiODfrb_x8h-aEM6SPzrchMmpzzLDszuKUK5IiyTKCsNMEv7R8Eo1C5fH2z0rE_TS3Y6mljO3R37mpAbJ6M-KU2arIndaJyRJx7ZNxgGZQHe9g1NXPc59ClW3WAt2SHNj-5OI_JdfG6HOUfheYimmR-IjeH1mkTqM_zCRiH_D8A3wAt9jBPq1bO0XB7v7egDrfT3gKC0mo6Te8CdgA1-_86JG93O42MUY6DLPsjg"
}