# For Job Posters: Add a Job Posting
POST http://localhost:3000/api/add-job HTTP/1.1
Content-Type: application/json

{
    "jobTitle":"Walmart Executive - 03",
    "description":"Manage and monitor day to day activies in Walmart",
    "deadline": 1648959990438,
    "workHours":8,
    "maxCapacity":5,
    "applied": 0,
    "location": "New Delhi, India",
    "token":"eyJhbGciOiJSUzI1NiIsImtpZCI6IjQ2NDExN2FjMzk2YmM3MWM4YzU5ZmI1MTlmMDEzZTJiNWJiNmM2ZTEiLCJ0eXAiOiJKV1QifQ.eyJ1c2VyVHlwZSI6IkpvYiBTZWVrZXIiLCJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vaG9tZWx5LWRiOGUyIiwiYXVkIjoiaG9tZWx5LWRiOGUyIiwiYXV0aF90aW1lIjoxNjQ4OTY0NDYyLCJ1c2VyX2lkIjoiajB5Rnl5dVNvNGRNTE16M2ZDaVBLbnNJbG45MiIsInN1YiI6ImoweUZ5eXVTbzRkTUxNejNmQ2lQS25zSWxuOTIiLCJpYXQiOjE2NDg5NjQ0NjIsImV4cCI6MTY0ODk2ODA2MiwiZW1haWwiOiJ3YW5nbmVsc29uMkBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsid2FuZ25lbHNvbjJAZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.pEvEhPQtmNGNOg_VIcXf5WrmqeNJFABOEYo-A6dZt_DwMvwqKeJ_-84z9LBeV9ScdnYttv7TznPKUS9E_0L_Cv76xasnhBbm04Nt7U8oZ_7SmEMnWLjFp1tAX_jDotBXxjSRONw0SBXuPEP17OZ3gb3n_1Z6hZWVXmb9Ccy35nr3TkAXYAThHe5YlNUsp82jPWWhFZXngyPD4nyOUxSsAWWsl8jAnBN77UKsoNdyj4sg5pwpzBg2vSIFOFyr0qBaQAKAe7FlPLMPUMkSO1uI4yHBDcg7uTVY5VHBvabjRmVP6HenGudJ7l2wbGzKWOn5HnnluXLvXJnW0i0gFX-5NQ"
}