POST http://localhost:3000/api/get-available-jobs
Content-Type: application/json

{
    "token":"eyJhbGciOiJSUzI1NiIsImtpZCI6IjQ2NDExN2FjMzk2YmM3MWM4YzU5ZmI1MTlmMDEzZTJiNWJiNmM2ZTEiLCJ0eXAiOiJKV1QifQ.eyJ1c2VyVHlwZSI6IkVtcGxveWVyIiwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2hvbWVseS1kYjhlMiIsImF1ZCI6ImhvbWVseS1kYjhlMiIsImF1dGhfdGltZSI6MTY0ODk4ODM2NywidXNlcl9pZCI6InF5TVJheHQxVVhmNmdZbFE1MExtc0FVd2xXWTIiLCJzdWIiOiJxeU1SYXh0MVVYZjZnWWxRNTBMbXNBVXdsV1kyIiwiaWF0IjoxNjQ4OTg4MzY3LCJleHAiOjE2NDg5OTE5NjcsImVtYWlsIjoid2FuZ25lbHNvbjJAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbIndhbmduZWxzb24yQGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.NF3YIRiuawjvB9X-apbdlpeeeuzqXhPQqmmbKqsrFUzgjWD0BjDf-Qf2KbsfP9vPN4viuZd4tP0mOthj0aD-bg72Y05qPvSLLCz9G7szmeMcVrMLvjdyXP14Hi3VMtpB_-Ffz86djeujY0EYz8JR1lTIimjK_JjESNz0CFHDoEHgTeRQOrvskZMBHnk9zI1MAwQpVBhnYzduV8cvPPWUOtO_lbZeaCCx49vHMmBnsAZ6r4Got994nW9sP9FI05cnhl2_Ek2PooMUN3cIPZRSkQYvDars-Ijb2VZxmmQbJDcNqfjrRzWeQDRFwxOhUgtfGANBQ8rzDWDkZRLiZvl3-w"
}