POST http://localhost:3000/api/get-available-jobs
Content-Type: application/json

{
      "token":"eyJhbGciOiJSUzI1NiIsImtpZCI6IjQ2NDExN2FjMzk2YmM3MWM4YzU5ZmI1MTlmMDEzZTJiNWJiNmM2ZTEiLCJ0eXAiOiJKV1QifQ.eyJ1c2VyVHlwZSI6IkFkbWluIiwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2hvbWVseS1kYjhlMiIsImF1ZCI6ImhvbWVseS1kYjhlMiIsImF1dGhfdGltZSI6MTY0ODk5MTg2NSwidXNlcl9pZCI6InF5TVJheHQxVVhmNmdZbFE1MExtc0FVd2xXWTIiLCJzdWIiOiJxeU1SYXh0MVVYZjZnWWxRNTBMbXNBVXdsV1kyIiwiaWF0IjoxNjQ4OTkxODY1LCJleHAiOjE2NDg5OTU0NjUsImVtYWlsIjoid2FuZ25lbHNvbjJAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbIndhbmduZWxzb24yQGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.NHTUxcdiBUbTUMpDU6LAFgJh3inTL_aGSrYdUO4cBlr-r_Bz-cABB7d-4em8dqQzx8sveymIh5O1-wnhfNZwaylYSOqfefsfLIWiQaTrGCQ9Taw6IDIXr2RpqgmTV82vMqtRJ8EvLBEMhNcIYOyrtZlzppNFc_NuwOWxf5_zruCfrgh2zDrqlsEWBmNVBmr1Yb0IS6BA96X5IZi7UQ8Qx71-0tpoLMK0PLhl1-5Ix4dFznfjLmDZisRG9qJ7hOSNZeMsv1zE7Q-V_XaptfalB2lG7nGQZw-qEjL60bR_pP1vykS4nMMrVm6dZvSZTfjzWwBpN4l6YEhFF_Vtiw2VrQ"
}