POST https://localhost:3000/api/update-homeless HTTP/1.1
Content-Type: application/json

{
    "homelessUser": {
        "name":"Shivam",
        "phoneNumber": {
            "countryCode":"+91",
            "number":"XXXXXXXXXX"
            }
    },
    "token":"eyJhbGciOiJSUzI1NiIsImtpZCI6IjQ2NDExN2FjMzk2YmM3MWM4YzU5ZmI1MTlmMDEzZTJiNWJiNmM2ZTEiLCJ0eXAiOiJKV1QifQ.eyJ1c2VyVHlwZSI6IkFkbWluIiwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2hvbWVseS1kYjhlMiIsImF1ZCI6ImhvbWVseS1kYjhlMiIsImF1dGhfdGltZSI6MTY0ODk5MDk4NSwidXNlcl9pZCI6InF5TVJheHQxVVhmNmdZbFE1MExtc0FVd2xXWTIiLCJzdWIiOiJxeU1SYXh0MVVYZjZnWWxRNTBMbXNBVXdsV1kyIiwiaWF0IjoxNjQ4OTkwOTg1LCJleHAiOjE2NDg5OTQ1ODUsImVtYWlsIjoid2FuZ25lbHNvbjJAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbIndhbmduZWxzb24yQGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.ASTaX8-D_w9x7j91hvKSExcnAao6YquOLL6FiMFJ5pXHkl1BdheXlXEOLaDjGasPcXB2MxFvp7G3qFvoN-KmDNUkDN5NgoSRa-d0sRN9St9rbQhFhaxjRNIpZ6zIFIN_U2eyWcFfng5m6dOHRuLJ3xCrWBU4RFYUax0fYdeNiVUVKObRHawYL0KjHxSjVC-K5klzIJPUvrCOtJ5zRi3dUQRJkPWuMvjXyqXGuTzahR1feRX520_GBkds-h9xMf0ns_CHiD8ZBSlpeMrGwoUd_ZX3XGBcIU2xmD17cIWrOGflGU0Iqs9ZJBbMT9iuOsWHWQEVlMmpG_O86YqtKE3kcA"
}