POST https://localhost:3000/api/update-homeless HTTP/1.1
Content-Type: application/json

{
    "homelessUser": {
        "name":"Shivam",
        "phoneNumber": {
            "countryCode":"+91",
            "number":"9655558174"
            }
    },
    "token":"eyJhbGciOiJSUzI1NiIsImtpZCI6IjQ2NDExN2FjMzk2YmM3MWM4YzU5ZmI1MTlmMDEzZTJiNWJiNmM2ZTEiLCJ0eXAiOiJKV1QifQ.eyJ1c2VyVHlwZSI6IkFkbWluIiwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2hvbWVseS1kYjhlMiIsImF1ZCI6ImhvbWVseS1kYjhlMiIsImF1dGhfdGltZSI6MTY0ODkzNzIyNywidXNlcl9pZCI6ImRla0JFRWxzWmJVRlQ1MmNZdEZnM21EVW1IOTIiLCJzdWIiOiJkZWtCRUVsc1piVUZUNTJjWXRGZzNtRFVtSDkyIiwiaWF0IjoxNjQ4OTYwMTI0LCJleHAiOjE2NDg5NjM3MjQsImVtYWlsIjoiYWN0aXZpdHkuc2Nob29sc2gyQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJhY3Rpdml0eS5zY2hvb2xzaDJAZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.js2lqrPB61Kpc31gCeqGe1fFMkds-7jDAL5NYdhSCbBmsOYURwGCMR_3ge0WldwzK42_AUk9FiOqsYd8I2JnaeQQPywVXxdSOF-W1U_7jLYxoSXVbhKfhM9-REjYa87wuu71-6v6T6YAPZrgocvs0ylAhzR-vCk50jxopkDocNpxc4U4qPOgT0Oi5T22uI10fu5gEyUmEDH9JjEnL104ouSid9J53KP_-pBlrIiG64yZXMluWnK1y7hBk2hLQl8YR-p6ftqisDWmhZ1S0u0Y0za4Nu48QG1_NPvVzaxy8RyXMJGUr2WKU2_67ZTW3sVcaOfjeQsVrDRSYX5mUIJRbQ"
}